### ISSUE TITLE
BUG: Some scripts cannot print the column headers when --include-column-headers is selected by the user

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#19]
**Example is _[utility-list-accounts-with-privileges.sh](https://raw.githubusercontent.com/webpwnized/gcp-audit/56aa998dc722cac428c352a5dba33b9bc6804080/utility-list-accounts-with-privileges.sh)_**

**In the HELP statement, the include headers options is not part of the help to the user**
```
declare ICH="False";
declare HELP=$(cat << EOL
	$0 [-r,--role] [-p, --project PROJECT] [--csv] [-d, --debug] [-h, --help]	
EOL
);
```

**The WHILE loop does not set the ICH to True, assuming the user provided the ICH flag**
```
while getopts "hdcip:r:" option
do 
    case "${option}"
        in
        r)
        	ROLE=${OPTARG};;
        p)
        	PROJECT_IDS=${OPTARG};;
        d)
        	DEBUG="True";;
        c)
        	CSV="True";;
        h)
        	echo $HELP; 
        	exit 0;;
    esac;
done;
```

**This code never runs because the ICH cannot be True**
```
    if [[ $ICH == "True" ]]; then
	echo "\"PROJECT_ID\", \"PROJECT_NAME\", \"PROJECT_OWNER\", \"PROJECT_APPLICATION\", \"ACCOUNT\", \"ACCOUNT_TYPE\", \"ENVIRONMENT\"";
    fi;

```

**Comment by ProGritz** [comment]
Corrections made to scripts in version 1.0.65, addressing missing code in the HELP statement and the WHILE loop for options
