### ISSUE TITLE
TODO: Add option to output only the Owner ID in utility-list-project-owners.sh

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#22]
In [utility-list-project-owners.sh](https://github.com/webpwnized/gcp-audit/blob/main/utility-list-project-owners.sh), the current script prints the Project Name and then the owner's ID. Please update the script to have a new option with short argument -o, and long argument --owner-only.

If the -o, --owner-only argument is passed, only output the $OWNER field (Do not output the Project Name).

**Comment by Hussain185** [comment]
Issue corrected with commit:
new option -o, --owner-only for outputting only the $Owner field

**Comment by webpwnized** [comment]
Fixed by @Hussain185
