### ISSUE TITLE
TODO: Migrate project configuration into a function

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#24]
Using [cis-6.6.1-cloud-sql-public-ips.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-6.6.1-cloud-sql-public-ips.sh) as an example, many scripts have the following line of code which sets the current project. This line is usually found inside a loop that is looping over each project. 

`gcloud config set project $PROJECT_ID 2>/dev/null;`

Migrate this line of code into a function. The function should be written in [functions.inc](https://github.com/webpwnized/gcp-audit/blob/main/functions.inc).

```
set_project(){
	local PROJECT_ID=$1;
	
	gcloud config set project $PROJECT_ID 2>/dev/null;
}
```

Once the function is tested and working as expected, replace all instances of the current line of code with a call to the function.

`set_project $PROJECT_ID`

**Comment by Hussain185** [comment]
Issue corrected with commit:
Migrate projects configuration into a function

**Comment by webpwnized** [comment]
Fixed by @Hussain185

**Comment by webpwnized** [comment]
Fixed by @Hussain185
