### ISSUE TITLE
TODO: Migrate listing projects into a function call

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#25]
Using [cis-6.6.1-cloud-sql-public-ips.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-6.6.1-cloud-sql-public-ips.sh) as an example, many scripts have the following line of code which gets a list of all projects.

declare PROJECT_IDS=$(gcloud projects list --format="flattened(PROJECT_ID)" | grep project_id | cut -d " " -f 2);

Migrate this line of code into a function. The function should be written in [functions.inc](https://github.com/webpwnized/gcp-audit/blob/main/functions.inc).

```
get_projects(){
	declare PROJECT_IDS=$(gcloud projects list --format="flattened(PROJECT_ID)" | grep project_id | cut -d " " -f 2);
}
```

Once the function is tested and working as expected, replace all instances of the current line of code with a call to the function.

`declare PROJECT_IDS=$(get_projects);`

**Comment by Hussain185** [comment]
Issue corrected with commit:
Migrate listing projects into a function call [e4bad8e]

**Comment by webpwnized** [comment]
Fixed by @Hussain185
