### ISSUE TITLE
Output Application Name in utility-list-project-owners.sh

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#27]
In [utility-list-project-owners.sh](https://github.com/webpwnized/gcp-audit/blob/main/utility-list-project-owners.sh), the current script collects the application name but never outputs the name. Please change line 13 as seen below.

`		echo "$NAME: $OWNER";
`

`		echo "$NAME ($APPLICATION): $OWNER";
`

**Comment by Hussain185** [comment]
Issue corrected with commit:
outputting application name

**Comment by webpwnized** [comment]
Fixed by @Hussain185
