### ISSUE TITLE
TODO: Add CSV, help output options to utility-list-project-owners.sh

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#28]
The [utility-list-project-owners.sh](https://github.com/webpwnized/gcp-audit/blob/main/utility-list-project-owners.sh) does not have the option to output as CSV and does not have the help output like other scripts. Using [cis-3.8.2-firewall-logs.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-3.8.2-firewall-logs.sh) as a model, add options for help, debug, and CSV to the script.

**Comment by Hussain185** [comment]
Issue corrected with commit:
adding options for help, debug, and CSV to the script

**Comment by webpwnized** [comment]
Fixed by @Hussain185
