### ISSUE TITLE
Add CSV output option to IP Forwarding script

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#32]
The script [cis-4.6.1-ip-forwarding-enabled.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-4.6.1-ip-forwarding-enabled.sh) does not have the CSV output option. The script is also in the old format with headers in the output making the script difficult to add CSV option in the current form. The script [cis-4.5.1-enabled-serial-ports.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-4.5.1-enabled-serial-ports.sh) is a good model of how the script should flow. Using the script for Serial Ports as a model, please add CSV output option to the script for IP forwarding.

**Comment by Hussain185** [comment]
Issue corrected with commit:
script is updated and CSV output option is added

**Comment by webpwnized** [comment]
Thanks for the fix!
