### ISSUE TITLE
Update script cis-3.8.2-firewall-logs.sh to fetch the list of Projects the same way that script cis-3.8.1-vpc-flow-logs.sh does

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#33]
Please update script [cis-3.8.2-firewall-logs.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-3.8.2-firewall-logs.sh) to fetch the list of Projects the same way that script [cis-3.8.1-vpc-flow-logs.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-3.8.1-vpc-flow-logs.sh) does (using the function call).

**Comment by Hussain185** [comment]
Issue corrected with commit:
fetch the list of Projects using function call

**Comment by webpwnized** [comment]
Thanks for the PR
