### ISSUE TITLE
Create a script that lists the Cloud Armor configuration files for each Project

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#35]
Create a new script **_cis-3.9.2-load-balancer-cloud-armor-policy.sh_**. Initially, this script should list each Cloud Armor Policy for each Project in the Organization. Improvements will be requested in future Issues. The existing script **[cis-3.9.1-load-balancer-tls-policy.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-3.9.1-load-balancer-tls-policy.sh)** is a good model to start with.

**Comment by Hussain185** [comment]
Issue corrected with commit:
this script list each Cloud Armor Policy for each Project

**Comment by webpwnized** [comment]
Nice PR!
