### ISSUE TITLE
Create a new script to list the logging status of each Cloud NAT Router Service (NATS)

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#36]
Using **[cis-3.8.2-firewall-logs.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-3.8.2-firewall-logs.sh)** as a model, create a new script that lists the current logging status for each Cloud NAT Service in each Project. The script should list whether the logging is enabled on the Cloud NAT Service.

**Comment by Hussain185** [comment]
Issue corrected with commit:
a new script to list the logging status of each Cloud NAT Router Service

**Comment by webpwnized** [comment]
Thanks for the enhancement
