### ISSUE TITLE
Create a new script to list the logging status of the DNS Policy on each VPC in each Project

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#37]
Using **[cis-3.8.1-vpc-flow-logs.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-3.8.1-vpc-flow-logs.sh)** as a model, create a new script that lists the current logging status for each DNS Policy on each VPC in each Project. The script should list whether the logging is enabled on the DNS Service for that respective VPC.

**Comment by Hussain185** [comment]
Issue corrected with commit:
new script list logging status of dns policy in each vpc on each project

**Comment by webpwnized** [comment]
Thanks for the enhancement
