### ISSUE TITLE
Create a new script to list the logging status for each Load Balancer in each Project

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#38]
Using **[cis-3.9.1-load-balancer-tls-policy.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-3.9.1-load-balancer-tls-policy.sh)** as a model, list whether logging is enabled on each Load Balancer in each Project in each Organization.

**Comment by Hussain185** [comment]
Issue corrected with commit:
a new script to list the logging status for each Load Balancer

**Comment by webpwnized** [comment]
Thanks for the help
