### ISSUE TITLE
BUG FIX: Some scripts are checking if the API is enabled before setting the Project

### ISSUE THREAD

**Issue by webpwnized** [webpwnized/gcp-audit#41]
Please verify that all scripts set the "current" project before attempting to test whether the relevant API is enabled. A working example is the following in which the project is set, then the API is checked. A working example is [cis-3.8.1-vpc-flow-logs.sh](https://github.com/webpwnized/gcp-audit/blob/main/cis-3.8.1-vpc-flow-logs.sh)

```
set_project $PROJECT_ID;

if ! api_enabled compute.googleapis.com ; then
	echo "Compute Engine API is not enabled on Project $PROJECT_ID";
	continue;
fi;
```

**Comment by Hussain185** [comment]
Issue corrected with commit:
new patch

**Comment by webpwnized** [comment]
Thanks for the help
