### ISSUE TITLE
Output Formats/Enabled API's

### ISSUE THREAD

**Issue by sSeld** [webpwnized/gcp-audit#9]
Are there any output formats you were planning to add other than CSV? I noticed that one was added. Maybe something akin to what Trivy provides. I'd be willing to help with any of these.

**Comment by webpwnized** [comment]
I would like to get CSV added to at least the CIS 4,5 and 6 scripts. These are the most used scripts. Currently, only the CIS 4.9.1 and CIS 4.9.2 scripts have CSV, but the feature is very useful. Also, the feature to check if the relevant API is enabled is a nice feature that is only on 3-4 scripts at this time.

**Comment by sSeld** [comment]
I'll go through and add the remaining enabled API logic for the other scripts.

**Comment by sSeld** [comment]
Any aversion to sourcing utility functions inside these cis scripts? Most of the API enabled logic is very repetitive so far. The downside is that this would create a dependency on a utility script for each cis script.

**Comment by webpwnized** [comment]
The utility scripts are "user interfaces" like the CIS scripts, so they would remain separate. However, it would be possible to create a function that implements some common functionality (i.e., get a list of projects), put the function into an include file, then include the include file in the CIS script. 

If there was a function get_projects() whose return value was a list of projects, that function could be in a file named projects.inc. projects.inc could be included in a CIS script using "source projects.inc". Then the function get_projects() could be called in the CIS file as if that function was local.

https://linuxize.com/post/bash-functions/
